version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "Nmrt@1234"
      MYSQL_DATABASE: cafe
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pNmrt@1234"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./Backend
    container_name: spring-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cafe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Nmrt@1234"
      SERVER_PORT: "8082"
    ports:
      - "8082:8082"

  frontend:
    build:
      context: ./Frontend
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
